import { ITEM_PARAMETERS } from './item-parameters';
import type { EventSchema } from './item-parameters';

export const ECOMMERCE_EVENTS: EventSchema[] = [
  {
    name: 'view_item_list',
    description: 'User views a list of items (category page, search results, recommendations)',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'item_list_id',
        displayName: 'Item List ID',
        type: 'string',
        required: false,
        placeholder: 'related_products',
        description: 'ID for this list (e.g., \'search_results\', \'homepage_featured\'). Used to compare list performance.',
      },
      {
        name: 'item_list_name',
        displayName: 'Item List Name',
        type: 'string',
        required: false,
        placeholder: 'Related Products',
        description: 'Human-readable list name shown in GA4 reports.',
      },
    ],
  },
  {
    name: 'select_item',
    description: 'User selects an item from a list',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'item_list_id',
        displayName: 'Item List ID',
        type: 'string',
        required: false,
        placeholder: 'related_products',
        description: 'ID of the list the item was clicked from — must match the list_id from view_item_list.',
      },
      {
        name: 'item_list_name',
        displayName: 'Item List Name',
        type: 'string',
        required: false,
        placeholder: 'Related Products',
        description: 'Display name of the list the item was selected from.',
      },
    ],
  },
  {
    name: 'view_item',
    description: 'User views an item detail page',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'currency',
        displayName: 'Currency',
        type: 'string',
        required: true,
        placeholder: 'USD',
        description: '3-letter currency code matching your store (e.g., USD, EUR, SEK). Must match the currency of the value field.',
        validation: { pattern: '^[A-Z]{3}$' },
      },
      {
        name: 'value',
        displayName: 'Value',
        type: 'number',
        required: true,
        placeholder: '29.99',
        description: 'Monetary value of the viewed item(s). Must be a number, not a string — GA4 silently drops string values.',
      },
    ],
  },
  {
    name: 'add_to_cart',
    description: 'User adds an item to the shopping cart',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'currency',
        displayName: 'Currency',
        type: 'string',
        required: true,
        placeholder: 'USD',
        description: '3-letter currency code matching your store (e.g., USD, EUR, SEK). Must match the currency of the value field.',
        validation: { pattern: '^[A-Z]{3}$' },
      },
      {
        name: 'value',
        displayName: 'Value',
        type: 'number',
        required: true,
        placeholder: '29.99',
        description: 'Total value of the item(s) added (price × quantity). Must be a number.',
      },
    ],
  },
  {
    name: 'remove_from_cart',
    description: 'User removes an item from the shopping cart',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'currency',
        displayName: 'Currency',
        type: 'string',
        required: true,
        placeholder: 'USD',
        description: '3-letter currency code matching your store (e.g., USD, EUR, SEK). Must match the currency of the value field.',
        validation: { pattern: '^[A-Z]{3}$' },
      },
      {
        name: 'value',
        displayName: 'Value',
        type: 'number',
        required: true,
        placeholder: '29.99',
        description: 'Total value of the item(s) removed. Must be a number.',
      },
    ],
  },
  {
    name: 'view_cart',
    description: 'User views the shopping cart',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'currency',
        displayName: 'Currency',
        type: 'string',
        required: true,
        placeholder: 'USD',
        description: '3-letter currency code matching your store (e.g., USD, EUR, SEK). Must match the currency of the value field.',
        validation: { pattern: '^[A-Z]{3}$' },
      },
      {
        name: 'value',
        displayName: 'Value',
        type: 'number',
        required: true,
        placeholder: '49.99',
        description: 'Total cart value. Must be a number — GA4 silently drops string values.',
      },
    ],
  },
  {
    name: 'begin_checkout',
    description: 'User begins the checkout process',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'currency',
        displayName: 'Currency',
        type: 'string',
        required: true,
        placeholder: 'USD',
        description: '3-letter currency code matching your store (e.g., USD, EUR, SEK). Must match the currency of the value field.',
        validation: { pattern: '^[A-Z]{3}$' },
      },
      {
        name: 'value',
        displayName: 'Value',
        type: 'number',
        required: true,
        placeholder: '49.99',
        description: 'Total checkout value including items, tax, and shipping. Must be a number.',
      },
      {
        name: 'coupon',
        displayName: 'Coupon',
        type: 'string',
        required: false,
        placeholder: 'SUMMER20',
        description: 'Order-level coupon code (e.g., \'SUMMER20\'). Item-level coupons go in the items array.',
      },
    ],
  },
  {
    name: 'add_shipping_info',
    description: 'User adds shipping information during checkout',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'currency',
        displayName: 'Currency',
        type: 'string',
        required: true,
        placeholder: 'USD',
        description: '3-letter currency code matching your store (e.g., USD, EUR, SEK). Must match the currency of the value field.',
        validation: { pattern: '^[A-Z]{3}$' },
      },
      {
        name: 'value',
        displayName: 'Value',
        type: 'number',
        required: true,
        placeholder: '49.99',
        description: 'Total order value at this checkout step. Must be a number.',
      },
      {
        name: 'coupon',
        displayName: 'Coupon',
        type: 'string',
        required: false,
        placeholder: 'SUMMER20',
        description: 'Coupon code applied to this order.',
      },
      {
        name: 'shipping_tier',
        displayName: 'Shipping Tier',
        type: 'string',
        required: false,
        placeholder: 'Standard',
        description: 'Shipping method the user selected (e.g., \'Standard\', \'Express\', \'Next Day\').',
      },
    ],
  },
  {
    name: 'add_payment_info',
    description: 'User adds payment information during checkout',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'currency',
        displayName: 'Currency',
        type: 'string',
        required: true,
        placeholder: 'USD',
        description: '3-letter currency code matching your store (e.g., USD, EUR, SEK). Must match the currency of the value field.',
        validation: { pattern: '^[A-Z]{3}$' },
      },
      {
        name: 'value',
        displayName: 'Value',
        type: 'number',
        required: true,
        placeholder: '49.99',
        description: 'Total order value at this checkout step. Must be a number.',
      },
      {
        name: 'coupon',
        displayName: 'Coupon',
        type: 'string',
        required: false,
        placeholder: 'SUMMER20',
        description: 'Coupon code applied to this order.',
      },
      {
        name: 'payment_type',
        displayName: 'Payment Type',
        type: 'string',
        required: false,
        placeholder: 'credit_card',
        description: 'How the user is paying. Select from common options or enter a custom value.',
        validation: {
          enum: ['credit_card', 'paypal', 'klarna', 'apple_pay', 'google_pay', 'bank_transfer'],
        },
      },
    ],
  },
  {
    name: 'purchase',
    description: 'User completes a purchase transaction',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'transaction_id',
        displayName: 'Transaction ID',
        type: 'string',
        required: true,
        placeholder: 'T-12345',
        description: 'Your order ID from your backend/CMS (e.g., Shopify order number). Must be unique per transaction — GA4 uses this to deduplicate revenue.',
      },
      {
        name: 'currency',
        displayName: 'Currency',
        type: 'string',
        required: true,
        placeholder: 'USD',
        description: '3-letter currency code matching your store (e.g., USD, EUR, SEK). Must match the currency of the value field.',
        validation: { pattern: '^[A-Z]{3}$' },
      },
      {
        name: 'value',
        displayName: 'Value',
        type: 'number',
        required: true,
        placeholder: '59.99',
        description: 'Total order revenue including tax and shipping. Must be a number — this is what GA4 reports as revenue.',
      },
      {
        name: 'tax',
        displayName: 'Tax',
        type: 'number',
        required: false,
        placeholder: '4.90',
        description: 'Tax amount for this order. Must be a number.',
      },
      {
        name: 'shipping',
        displayName: 'Shipping',
        type: 'number',
        required: false,
        placeholder: '5.00',
        description: 'Shipping cost for this order. Must be a number.',
      },
      {
        name: 'coupon',
        displayName: 'Coupon',
        type: 'string',
        required: false,
        placeholder: 'SUMMER20',
        description: 'Order-level coupon code applied to this purchase.',
      },
      {
        name: 'affiliation',
        displayName: 'Affiliation',
        type: 'string',
        required: false,
        placeholder: 'Google Store',
        description: 'Store or partner that fulfilled this order (e.g., \'Google Store\', \'Partner Marketplace\').',
      },
    ],
  },
  {
    name: 'refund',
    description: 'A refund is issued for a previous purchase',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'transaction_id',
        displayName: 'Transaction ID',
        type: 'string',
        required: true,
        placeholder: 'T-12345',
        description: 'The transaction_id from the original purchase event. GA4 matches refunds to purchases using this ID.',
      },
      {
        name: 'currency',
        displayName: 'Currency',
        type: 'string',
        required: true,
        placeholder: 'USD',
        description: '3-letter currency code matching your store (e.g., USD, EUR, SEK). Must match the currency of the value field.',
        validation: { pattern: '^[A-Z]{3}$' },
      },
      {
        name: 'value',
        displayName: 'Value',
        type: 'number',
        required: true,
        placeholder: '59.99',
        description: 'Refunded amount. For partial refunds, include only the refunded items in the items array.',
      },
      {
        name: 'tax',
        displayName: 'Tax',
        type: 'number',
        required: false,
        placeholder: '4.90',
        description: 'Tax portion of the refund. Must be a number.',
      },
      {
        name: 'shipping',
        displayName: 'Shipping',
        type: 'number',
        required: false,
        placeholder: '5.00',
        description: 'Shipping portion of the refund. Must be a number.',
      },
    ],
  },
  {
    name: 'view_promotion',
    description: 'User views a promotion or banner',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'promotion_id',
        displayName: 'Promotion ID',
        type: 'string',
        required: false,
        placeholder: 'PROMO-001',
        description: 'Identifier for the promotion',
      },
      {
        name: 'promotion_name',
        displayName: 'Promotion Name',
        type: 'string',
        required: false,
        placeholder: 'Summer Sale',
        description: 'Display name for the promotion',
      },
      {
        name: 'creative_name',
        displayName: 'Creative Name',
        type: 'string',
        required: false,
        placeholder: 'summer_banner_v2',
        description: 'Name of the creative asset',
      },
      {
        name: 'creative_slot',
        displayName: 'Creative Slot',
        type: 'string',
        required: false,
        placeholder: 'hero_banner',
        description: 'Slot or position where the creative is shown',
      },
    ],
  },
  {
    name: 'select_promotion',
    description: 'User clicks on a promotion or banner',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'promotion_id',
        displayName: 'Promotion ID',
        type: 'string',
        required: false,
        placeholder: 'PROMO-001',
        description: 'Identifier for the promotion',
      },
      {
        name: 'promotion_name',
        displayName: 'Promotion Name',
        type: 'string',
        required: false,
        placeholder: 'Summer Sale',
        description: 'Display name for the promotion',
      },
      {
        name: 'creative_name',
        displayName: 'Creative Name',
        type: 'string',
        required: false,
        placeholder: 'summer_banner_v2',
        description: 'Name of the creative asset',
      },
      {
        name: 'creative_slot',
        displayName: 'Creative Slot',
        type: 'string',
        required: false,
        placeholder: 'hero_banner',
        description: 'Slot or position where the creative is shown',
      },
    ],
  },
];
