import { ITEM_PARAMETERS } from './item-parameters';
import type { EventSchema } from './item-parameters';

export const ECOMMERCE_EVENTS: EventSchema[] = [
  {
    name: 'view_item_list',
    description: 'User views a list of items (category page, search results, recommendations)',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'item_list_id',
        displayName: 'Item List ID',
        type: 'string',
        required: false,
        placeholder: 'related_products',
        description: 'Identifier for the list',
      },
      {
        name: 'item_list_name',
        displayName: 'Item List Name',
        type: 'string',
        required: false,
        placeholder: 'Related Products',
        description: 'Display name for the list',
      },
    ],
  },
  {
    name: 'select_item',
    description: 'User selects an item from a list',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'item_list_id',
        displayName: 'Item List ID',
        type: 'string',
        required: false,
        placeholder: 'related_products',
        description: 'Identifier for the list the item was selected from',
      },
      {
        name: 'item_list_name',
        displayName: 'Item List Name',
        type: 'string',
        required: false,
        placeholder: 'Related Products',
        description: 'Display name for the list',
      },
    ],
  },
  {
    name: 'view_item',
    description: 'User views an item detail page',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'currency',
        displayName: 'Currency',
        type: 'string',
        required: true,
        placeholder: 'USD',
        description: 'ISO 4217 currency code',
        validation: { pattern: '^[A-Z]{3}$' },
      },
      {
        name: 'value',
        displayName: 'Value',
        type: 'number',
        required: true,
        placeholder: '29.99',
        description: 'Monetary value of the event',
      },
    ],
  },
  {
    name: 'add_to_cart',
    description: 'User adds an item to the shopping cart',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'currency',
        displayName: 'Currency',
        type: 'string',
        required: true,
        placeholder: 'USD',
        description: 'ISO 4217 currency code',
        validation: { pattern: '^[A-Z]{3}$' },
      },
      {
        name: 'value',
        displayName: 'Value',
        type: 'number',
        required: true,
        placeholder: '29.99',
        description: 'Monetary value of the item(s) added',
      },
    ],
  },
  {
    name: 'remove_from_cart',
    description: 'User removes an item from the shopping cart',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'currency',
        displayName: 'Currency',
        type: 'string',
        required: true,
        placeholder: 'USD',
        description: 'ISO 4217 currency code',
        validation: { pattern: '^[A-Z]{3}$' },
      },
      {
        name: 'value',
        displayName: 'Value',
        type: 'number',
        required: true,
        placeholder: '29.99',
        description: 'Monetary value of the item(s) removed',
      },
    ],
  },
  {
    name: 'view_cart',
    description: 'User views the shopping cart',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'currency',
        displayName: 'Currency',
        type: 'string',
        required: true,
        placeholder: 'USD',
        description: 'ISO 4217 currency code',
        validation: { pattern: '^[A-Z]{3}$' },
      },
      {
        name: 'value',
        displayName: 'Value',
        type: 'number',
        required: true,
        placeholder: '49.99',
        description: 'Total monetary value of the cart',
      },
    ],
  },
  {
    name: 'begin_checkout',
    description: 'User begins the checkout process',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'currency',
        displayName: 'Currency',
        type: 'string',
        required: true,
        placeholder: 'USD',
        description: 'ISO 4217 currency code',
        validation: { pattern: '^[A-Z]{3}$' },
      },
      {
        name: 'value',
        displayName: 'Value',
        type: 'number',
        required: true,
        placeholder: '49.99',
        description: 'Monetary value of the checkout',
      },
      {
        name: 'coupon',
        displayName: 'Coupon',
        type: 'string',
        required: false,
        placeholder: 'SUMMER20',
        description: 'Coupon code applied at checkout',
      },
    ],
  },
  {
    name: 'add_shipping_info',
    description: 'User adds shipping information during checkout',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'currency',
        displayName: 'Currency',
        type: 'string',
        required: true,
        placeholder: 'USD',
        description: 'ISO 4217 currency code',
        validation: { pattern: '^[A-Z]{3}$' },
      },
      {
        name: 'value',
        displayName: 'Value',
        type: 'number',
        required: true,
        placeholder: '49.99',
        description: 'Monetary value of the order',
      },
      {
        name: 'coupon',
        displayName: 'Coupon',
        type: 'string',
        required: false,
        placeholder: 'SUMMER20',
        description: 'Coupon code applied',
      },
      {
        name: 'shipping_tier',
        displayName: 'Shipping Tier',
        type: 'string',
        required: false,
        placeholder: 'Standard',
        description: 'Shipping tier selected (e.g. Ground, Express)',
      },
    ],
  },
  {
    name: 'add_payment_info',
    description: 'User adds payment information during checkout',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'currency',
        displayName: 'Currency',
        type: 'string',
        required: true,
        placeholder: 'USD',
        description: 'ISO 4217 currency code',
        validation: { pattern: '^[A-Z]{3}$' },
      },
      {
        name: 'value',
        displayName: 'Value',
        type: 'number',
        required: true,
        placeholder: '49.99',
        description: 'Monetary value of the order',
      },
      {
        name: 'coupon',
        displayName: 'Coupon',
        type: 'string',
        required: false,
        placeholder: 'SUMMER20',
        description: 'Coupon code applied',
      },
      {
        name: 'payment_type',
        displayName: 'Payment Type',
        type: 'string',
        required: false,
        placeholder: 'credit_card',
        description: 'Payment method selected',
        validation: {
          enum: ['credit_card', 'paypal', 'klarna', 'apple_pay', 'google_pay', 'bank_transfer'],
        },
      },
    ],
  },
  {
    name: 'purchase',
    description: 'User completes a purchase transaction',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'transaction_id',
        displayName: 'Transaction ID',
        type: 'string',
        required: true,
        placeholder: 'T-12345',
        description: 'Unique transaction identifier',
      },
      {
        name: 'currency',
        displayName: 'Currency',
        type: 'string',
        required: true,
        placeholder: 'USD',
        description: 'ISO 4217 currency code',
        validation: { pattern: '^[A-Z]{3}$' },
      },
      {
        name: 'value',
        displayName: 'Value',
        type: 'number',
        required: true,
        placeholder: '59.99',
        description: 'Total order value (revenue)',
      },
      {
        name: 'tax',
        displayName: 'Tax',
        type: 'number',
        required: false,
        placeholder: '4.90',
        description: 'Tax amount',
      },
      {
        name: 'shipping',
        displayName: 'Shipping',
        type: 'number',
        required: false,
        placeholder: '5.00',
        description: 'Shipping cost',
      },
      {
        name: 'coupon',
        displayName: 'Coupon',
        type: 'string',
        required: false,
        placeholder: 'SUMMER20',
        description: 'Coupon code applied to the transaction',
      },
      {
        name: 'affiliation',
        displayName: 'Affiliation',
        type: 'string',
        required: false,
        placeholder: 'Google Store',
        description: 'Store or affiliation from which this transaction occurred',
      },
    ],
  },
  {
    name: 'refund',
    description: 'A refund is issued for a previous purchase',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'transaction_id',
        displayName: 'Transaction ID',
        type: 'string',
        required: true,
        placeholder: 'T-12345',
        description: 'Transaction ID of the original purchase',
      },
      {
        name: 'currency',
        displayName: 'Currency',
        type: 'string',
        required: true,
        placeholder: 'USD',
        description: 'ISO 4217 currency code',
        validation: { pattern: '^[A-Z]{3}$' },
      },
      {
        name: 'value',
        displayName: 'Value',
        type: 'number',
        required: true,
        placeholder: '59.99',
        description: 'Refunded amount',
      },
      {
        name: 'tax',
        displayName: 'Tax',
        type: 'number',
        required: false,
        placeholder: '4.90',
        description: 'Refunded tax amount',
      },
      {
        name: 'shipping',
        displayName: 'Shipping',
        type: 'number',
        required: false,
        placeholder: '5.00',
        description: 'Refunded shipping cost',
      },
    ],
  },
  {
    name: 'view_promotion',
    description: 'User views a promotion or banner',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'promotion_id',
        displayName: 'Promotion ID',
        type: 'string',
        required: false,
        placeholder: 'PROMO-001',
        description: 'Identifier for the promotion',
      },
      {
        name: 'promotion_name',
        displayName: 'Promotion Name',
        type: 'string',
        required: false,
        placeholder: 'Summer Sale',
        description: 'Display name for the promotion',
      },
      {
        name: 'creative_name',
        displayName: 'Creative Name',
        type: 'string',
        required: false,
        placeholder: 'summer_banner_v2',
        description: 'Name of the creative asset',
      },
      {
        name: 'creative_slot',
        displayName: 'Creative Slot',
        type: 'string',
        required: false,
        placeholder: 'hero_banner',
        description: 'Slot or position where the creative is shown',
      },
    ],
  },
  {
    name: 'select_promotion',
    description: 'User clicks on a promotion or banner',
    category: 'ecommerce',
    isEcommerce: true,
    hasItems: true,
    itemParameters: ITEM_PARAMETERS,
    parameters: [
      {
        name: 'promotion_id',
        displayName: 'Promotion ID',
        type: 'string',
        required: false,
        placeholder: 'PROMO-001',
        description: 'Identifier for the promotion',
      },
      {
        name: 'promotion_name',
        displayName: 'Promotion Name',
        type: 'string',
        required: false,
        placeholder: 'Summer Sale',
        description: 'Display name for the promotion',
      },
      {
        name: 'creative_name',
        displayName: 'Creative Name',
        type: 'string',
        required: false,
        placeholder: 'summer_banner_v2',
        description: 'Name of the creative asset',
      },
      {
        name: 'creative_slot',
        displayName: 'Creative Slot',
        type: 'string',
        required: false,
        placeholder: 'hero_banner',
        description: 'Slot or position where the creative is shown',
      },
    ],
  },
];
