import type { EventSchema } from './item-parameters';

export const RECOMMENDED_EVENTS: EventSchema[] = [
  {
    name: 'login',
    description: 'User logs in to the site or app',
    category: 'engagement',
    isEcommerce: false,
    hasItems: false,
    parameters: [
      {
        name: 'method',
        displayName: 'Method',
        type: 'string',
        required: false,
        placeholder: 'Google',
        description: 'How the user logged in (e.g., \'Google\', \'Email\', \'Facebook\'). Use consistent values across login and sign_up events.',
      },
    ],
  },
  {
    name: 'sign_up',
    description: 'User registers a new account',
    category: 'engagement',
    isEcommerce: false,
    hasItems: false,
    parameters: [
      {
        name: 'method',
        displayName: 'Method',
        type: 'string',
        required: false,
        placeholder: 'Email',
        description: 'How the user signed up (e.g., \'Email\', \'Google\', \'Facebook\'). Use the same values as your login event for consistency.',
      },
    ],
  },
  {
    name: 'search',
    description: 'User performs a search on the site',
    category: 'engagement',
    isEcommerce: false,
    hasItems: false,
    parameters: [
      {
        name: 'search_term',
        displayName: 'Search Term',
        type: 'string',
        required: true,
        placeholder: 'blue shoes',
        description: 'The exact search query the user entered. GA4 shows this in the search terms report.',
      },
    ],
  },
  {
    name: 'generate_lead',
    description: 'User submits a form or expresses interest (lead generation)',
    category: 'engagement',
    isEcommerce: false,
    hasItems: false,
    parameters: [
      {
        name: 'currency',
        displayName: 'Currency',
        type: 'string',
        required: false,
        placeholder: 'USD',
        description: '3-letter currency code for the lead value (e.g., USD, EUR, SEK). Required if you set a value.',
        validation: { pattern: '^[A-Z]{3}$' },
      },
      {
        name: 'value',
        displayName: 'Value',
        type: 'number',
        required: false,
        placeholder: '100.00',
        description: 'Estimated value of this lead. Used by Google Ads for Smart Bidding optimization. Must be a number.',
      },
    ],
  },
  {
    name: 'share',
    description: 'User shares content via social or messaging',
    category: 'engagement',
    isEcommerce: false,
    hasItems: false,
    parameters: [
      {
        name: 'method',
        displayName: 'Method',
        type: 'string',
        required: false,
        placeholder: 'Twitter',
        description: 'How the content was shared (e.g., \'Twitter\', \'Email\', \'WhatsApp\', \'Copy Link\').',
      },
      {
        name: 'content_type',
        displayName: 'Content Type',
        type: 'string',
        required: false,
        placeholder: 'article',
        description: 'Category of shared content (e.g., \'article\', \'product\', \'video\').',
      },
      {
        name: 'item_id',
        displayName: 'Item ID',
        type: 'string',
        required: false,
        placeholder: 'post-123',
        description: 'Unique ID of the content being shared. Helps track which content gets shared most.',
      },
    ],
  },
  {
    name: 'select_content',
    description: 'User selects a piece of content',
    category: 'engagement',
    isEcommerce: false,
    hasItems: false,
    parameters: [
      {
        name: 'content_type',
        displayName: 'Content Type',
        type: 'string',
        required: false,
        placeholder: 'article',
        description: 'Category of selected content (e.g., \'article\', \'video\', \'tab\').',
      },
      {
        name: 'content_id',
        displayName: 'Content ID',
        type: 'string',
        required: false,
        placeholder: 'post-123',
        description: 'Unique identifier for the content the user interacted with.',
      },
    ],
  },
];
