import type { EventSchema } from './item-parameters';

export const RECOMMENDED_EVENTS: EventSchema[] = [
  {
    name: 'login',
    description: 'User logs in to the site or app',
    category: 'engagement',
    isEcommerce: false,
    hasItems: false,
    parameters: [
      {
        name: 'method',
        displayName: 'Method',
        type: 'string',
        required: false,
        placeholder: 'Google',
        description: 'Method used to log in (e.g. Google, Email, Facebook)',
      },
    ],
  },
  {
    name: 'sign_up',
    description: 'User registers a new account',
    category: 'engagement',
    isEcommerce: false,
    hasItems: false,
    parameters: [
      {
        name: 'method',
        displayName: 'Method',
        type: 'string',
        required: false,
        placeholder: 'Email',
        description: 'Method used to sign up (e.g. Email, Google, Facebook)',
      },
    ],
  },
  {
    name: 'search',
    description: 'User performs a search on the site',
    category: 'engagement',
    isEcommerce: false,
    hasItems: false,
    parameters: [
      {
        name: 'search_term',
        displayName: 'Search Term',
        type: 'string',
        required: true,
        placeholder: 'blue shoes',
        description: 'The term the user searched for',
      },
    ],
  },
  {
    name: 'generate_lead',
    description: 'User submits a form or expresses interest (lead generation)',
    category: 'engagement',
    isEcommerce: false,
    hasItems: false,
    parameters: [
      {
        name: 'currency',
        displayName: 'Currency',
        type: 'string',
        required: false,
        placeholder: 'USD',
        description: 'ISO 4217 currency code for the lead value',
        validation: { pattern: '^[A-Z]{3}$' },
      },
      {
        name: 'value',
        displayName: 'Value',
        type: 'number',
        required: false,
        placeholder: '100.00',
        description: 'Estimated monetary value of the lead',
      },
    ],
  },
  {
    name: 'share',
    description: 'User shares content via social or messaging',
    category: 'engagement',
    isEcommerce: false,
    hasItems: false,
    parameters: [
      {
        name: 'method',
        displayName: 'Method',
        type: 'string',
        required: false,
        placeholder: 'Twitter',
        description: 'Share method or channel (e.g. Twitter, Email, WhatsApp)',
      },
      {
        name: 'content_type',
        displayName: 'Content Type',
        type: 'string',
        required: false,
        placeholder: 'article',
        description: 'Type of content being shared',
      },
      {
        name: 'item_id',
        displayName: 'Item ID',
        type: 'string',
        required: false,
        placeholder: 'post-123',
        description: 'ID of the content being shared',
      },
    ],
  },
  {
    name: 'select_content',
    description: 'User selects a piece of content',
    category: 'engagement',
    isEcommerce: false,
    hasItems: false,
    parameters: [
      {
        name: 'content_type',
        displayName: 'Content Type',
        type: 'string',
        required: false,
        placeholder: 'article',
        description: 'Type of the selected content',
      },
      {
        name: 'content_id',
        displayName: 'Content ID',
        type: 'string',
        required: false,
        placeholder: 'post-123',
        description: 'Identifier for the selected content',
      },
    ],
  },
];
